version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: zimche-postgres
    environment:
      POSTGRES_DB: zimche_audit_dev
      POSTGRES_USER: zimche_user
      POSTGRES_PASSWORD: zimche_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "effective_cache_size=1GB"
      - "-c"
      - "work_mem=4MB"
      - "-c"
      - "maintenance_work_mem=64MB"
      - "-c"
      - "checkpoint_completion_target=0.7"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: zimche-audit-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DB_USERNAME: zimche_user
      DB_PASSWORD: zimche_password
      JWT_SECRET: your-jwt-secret-key
      OPENAI_API_KEY: your-openai-api-key

volumes:
  postgres_data:
